apiVersion: v1
kind: Service
metadata:
  name: loan-prediction-backend-service
  namespace: default
  labels:
    app: loan-prediction
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: loan-prediction
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: loan-prediction-frontend-service
  namespace: default
  labels:
    app: loan-prediction
    component: ui
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: loan-prediction
    component: ui
